# Generated by Django 4.2.2 on 2023-08-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0002_rename_age_choices_profile_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], max_length=10),
        ),
    ]
